export const partyDares = [
    "Sing a song chosen by the group.",
    "Do a silly dance for 30 seconds.",
    "Let someone in the group write a word on your forehead with a marker.",
    "Speak in an accent chosen by the group for the next 10 minutes.",
    "Attempt to juggle three items chosen by the group.",
    "Do your best impersonation of someone in the room.",
    "Let the group choose a person for you to text and what to say.",
    "Wear socks on your hands for the next 10 minutes.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.)",
    "Let someone give you a new hairstyle.",
    "Do 20 push-ups.",
    "Try to lick your elbow.",
    "Let someone tickle you for 30 seconds.",
    "Talk like a baby for the next 5 minutes.",
    "Attempt to breakdance for 1 minute.",
    "Sing a song chosen by the group.",
    "Do a silly dance for 30 seconds.",
    "Let someone in the group write a word on your forehead with a marker.",
    "Speak in an accent chosen by the group for the next 10 minutes.",
    "Attempt to juggle three items chosen by the group.",
    "Do your best impersonation of someone in the room.",
    "Let the group choose a person for you to text and what to say.",
    "Wear socks on your hands for the next 10 minutes.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.)",
    "Let someone give you a new hairstyle.",
    "Do 20 push-ups.",
    "Try to lick your elbow.",
    "Let someone tickle you for 30 seconds.",
    "Talk like a baby for the next 5 minutes.",
    "Attempt to breakdance for 1 minute.",
  
    "Sing a song chosen by the group.",
    "Do a silly dance for 30 seconds.",
    "Let someone in the group write a word on your forehead with a marker.",
    "Speak in an accent chosen by the group for the next 10 minutes.",
    "Attempt to juggle three items chosen by the group.",
    "Do your best impersonation of someone in the room.",
    "Let the group choose a person for you to text and what to say.",
    "Wear socks on your hands for the next 10 minutes.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.)",
    "Let someone give you a new hairstyle.",
    "Do 20 push-ups.",
    "Try to lick your elbow.",
    "Let someone tickle you for 30 seconds.",
    "Talk like a baby for the next 5 minutes.",
    "Attempt to breakdance for 1 minute.",
    
    "Sing a song chosen by the group.",
    "Do a silly dance for 30 seconds.",
    "Let someone in the group write a word on your forehead with a marker.",
    "Speak in an accent chosen by the group for the next 10 minutes.",
    "Attempt to juggle three items chosen by the group.",
    "Do your best impersonation of someone in the room.",
    "Let the group choose a person for you to text and what to say.",
    "Wear socks on your hands for the next 10 minutes.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.)",
    "Let someone give you a new hairstyle.",
    "Do 20 push-ups.",
    "Try to lick your elbow.",
    "Let someone tickle you for 30 seconds.",
    "Talk like a baby for the next 5 minutes.",
    "Attempt to breakdance for 1 minute.",
    
    "Sing a song chosen by the group.",
    "Do a silly dance for 30 seconds.",
    "Let someone in the group write a word on your forehead with a marker.",
    "Speak in an accent chosen by the group for the next 10 minutes.",
    "Attempt to juggle three items chosen by the group.",
    "Do your best impersonation of someone in the room.",
    "Let the group choose a person for you to text and what to say.",
    "Wear socks on your hands for the next 10 minutes.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.)",
    "Let someone give you a new hairstyle.",
    "Do 20 push-ups.",
    "Try to lick your elbow.",
    "Let someone tickle you for 30 seconds.",
    "Talk like a baby for the next 5 minutes.",
    "Attempt to breakdance for 1 minute.",
    
    "Sing a song chosen by the group.",
    "Do a silly dance for 30 seconds.",
    "Let someone in the group write a word on your forehead with a marker.",
    "Speak in an accent chosen by the group for the next 10 minutes.",
    "Attempt to juggle three items chosen by the group.",
    "Do your best impersonation of someone in the room.",
    "Let the group choose a person for you to text and what to say.",
    "Wear socks on your hands for the next 10 minutes.",
    "Eat a spoonful of a condiment (ketchup, mustard, etc.)",
    "Let someone give you a new hairstyle.",
    "Do 20 push-ups.",
    "Try to lick your elbow.",
    "Let someone tickle you for 30 seconds.",
    "Talk like a baby for the next 5 minutes.",
    "Attempt to breakdance for 1 minute.",
  ];